name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - "!*"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"
      - name: Release
        if: github.event_name != 'workflow_dispatch'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ github.token }}
          prerelease: false
          files: |
            dist/script.user.js
      - name: Trigger Greasy Fork synchronization
        uses: antaljanosbenjamin/single-commit-publish@v1.0.1
        with:
          github-token: ${{ github.token }}
          branch: dist
          source-dir: dist
          files-and-dirs: "script.user.js script.meta.js"
          commit-message: ${{ github.ref_name }}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: true
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
